services:
  - type: web
    name: cdb-monitor
    env: python
    plan: free
    buildCommand: ./render-build.sh
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        sync: false
